#!/usr/bin/env python3
"""Writes include/edgeneuro/control/mearm_angle_data.hpp (the two measured link-angle lines) and data/real_golden.csv
(sensors -> real (shoulder, elbow, base) pulses through mearm_real in its default mode -- height_reach since 2026-10-03) for the C++ port's parity test.

    python3 tools/mujoco_bridge/gen_real_golden.py
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import mearm_pathb as pb  # noqa: E402
import mearm_real as real  # noqa: E402
import test_mearm_direction as fx  # noqa: E402

ROOT = HERE.parent.parent
HEADER = ROOT / "include" / "edgeneuro" / "control" / "mearm_angle_data.hpp"
GOLDEN = ROOT / "data" / "real_golden.csv"


def render():
    arm = real.load_arm()
    a = arm.angles
    header = f'''#pragma once

// GENERATED by tools/mujoco_bridge/gen_real_golden.py from {real.ANGLE_FILE.name}
// -- do not edit by hand (tools/mujoco_bridge/test_real_golden.py fails if this file is stale).
//
// The real MEArm's link elevations (degrees above horizontal) against servo pulse width, measured with a phone
// inclinometer (SESSION_LOG 2026-09-27):  elevation = at_1500 + slope * (pulse - 1500).

namespace edgeneuro::mearm::angle_data {{

constexpr float kUpperArmAt1500Deg = {a.shoulder["at_1500"]:.9f}f;
constexpr float kUpperArmSlopeDegPerUs = {a.shoulder["slope"]:.9f}f;
constexpr float kForearmAt1500Deg = {a.elbow["at_1500"]:.9f}f;
constexpr float kForearmSlopeDegPerUs = {a.elbow["slope"]:.9f}f;

}}  // namespace edgeneuro::mearm::angle_data
'''
    cal = pb.make_calibration(fx.SAVED_9_13)
    raws = list(fx.REAL_LOG_2026_09_24) + [fx.HANG, fx.FORWARD, fx.LEFT, fx.RIGHT,
                                           tuple(-c for c in fx.HANG), fx._slerp(fx.HANG, fx.FORWARD, 0.5)]
    # a sweep of the raise. /21, not /20: with the 1500..1950 shoulder range (2026-09-28) a /20 grid put every other pose
    # EXACTLY on x.5 us (450 * 0.05 = 22.5), where float and double break the tie differently -- a grid artifact
    raws += [fx._slerp(fx.HANG, fx.FORWARD, i / 21) for i in range(22)]
    bends = (fx.STRAIGHT, fx.STRAIGHT + 0.5, fx.STRAIGHT + 1.2, fx.FLEXED, 0.0, 3.1)
    lines = ["ax,ay,az,elbow_bend,shoulder_us,elbow_us,base_us"]
    for raw in raws:
        for bend in bends:
            s, e = real.pulses(arm, cal, raw, bend)               # the default mode: what the firmware runs
            b = real.base_pulse(cal, raw)
            lines.append(f"{raw[0]:.9f},{raw[1]:.9f},{raw[2]:.9f},{bend:.9f},{s},{e},{b}")
    return header, "\n".join(lines) + "\n"


def write(header_path=HEADER, golden_path=GOLDEN):
    header, golden = render()
    Path(header_path).parent.mkdir(parents=True, exist_ok=True)
    Path(golden_path).parent.mkdir(parents=True, exist_ok=True)
    Path(header_path).write_text(header)
    Path(golden_path).write_text(golden)


if __name__ == "__main__":
    write()
    print(f"wrote {HEADER}\nwrote {GOLDEN}")
