#!/usr/bin/env python3
"""Compiles the BOOT calibration into the firmware: writes include/edgeneuro/control/mearm_calibration_data.hpp from the
committed golden calibration data/shoulder_calibration_golden_2026-09-13.json (HANG / FORWARD / LEFT / RIGHT upper-arm
vectors + the straight-arm elbow reading). Since 2026-10-03 run_demo_live.py SENDS the current calibration over UART
(mearm_calibration_link.py), so a re-calibration needs no re-flash; this is only what the board uses until then, and the
C++ tests' fixture. Refuses a calibration Path B would reject.

    python3 tools/mujoco_bridge/gen_calibration_header.py
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import mearm_pathb as pb  # noqa: E402
import mearm_real as real  # noqa: E402

DEFAULT_SOURCE = HERE.parent.parent / "data" / "shoulder_calibration_golden_2026-09-13.json"
HEADER = HERE.parent.parent / "include" / "edgeneuro" / "control" / "mearm_calibration_data.hpp"


def render(saved):
    cal = pb.make_calibration(saved)                            # raises KeyError / ValueError: never write a bad one
    has_reach = real.saved_base_reach(cal, saved) is not None   # raises ValueError for a reach Path B cannot use
    rows = []
    for name, key in (("Hang", "baseline_raw"), ("Forward", "forward_raw"), ("Left", "left_twist_raw"),
                      ("Right", "right_twist_raw")):
        for axis, v in zip("XYZ", saved[key]):
            rows.append(f"constexpr float k{name}{axis} = {float(v):.9f}f;")
    rows.append(f"constexpr float kZeroElbow = {float(saved['zero_elbow']):.9f}f;")
    # the arm's comfortable left/right reach (2026-10-03; no tool captures it yet): where the base hits its ends
    rows.append(f"constexpr bool kHasBaseReach = {'true' if has_reach else 'false'};")
    for name, key in (("BaseReachLeft", "base_reach_left_raw"), ("BaseReachRight", "base_reach_right_raw")):
        for axis, v in zip("XYZ", saved[key] if has_reach else (0.0, 0.0, 0.0)):
            rows.append(f"constexpr float k{name}{axis} = {float(v):.9f}f;")
    body = "\n".join(rows)
    return f'''#pragma once

// GENERATED by tools/mujoco_bridge/gen_calibration_header.py from the golden calibration
// (captured {saved.get("captured_at", "at an unknown time")}) -- do not edit by hand. Only what the board BOOTS with: a
// fresh calibration reaches it over UART from run_demo_live.py (mearm_calibration_link), no re-flash needed.
//
// The upper-arm IMU's raw gravity vectors (g) at the calibration poses HANG / FORWARD / LEFT_TWIST / RIGHT_TWIST, and the
// firmware's elbow reading (rad) with the arm straight: what mearm::pathb::Calibration is built from on the chip. Plus
// the arm's comfortable left/right reach (raw vectors), where the base hits its ends -- or kHasBaseReach = false.

namespace edgeneuro::mearm::calibration_data {{

{body}

}}  // namespace edgeneuro::mearm::calibration_data
'''


def write(source=DEFAULT_SOURCE, header=HEADER):
    text = render(json.loads(Path(source).read_text()))
    Path(header).parent.mkdir(parents=True, exist_ok=True)
    Path(header).write_text(text)
    return header


if __name__ == "__main__":
    print(f"wrote {write()}")
