// PulseEnvelope: the clamp that keeps the real MEArm's (shoulder, elbow) servo pulses inside the envelope measured on
// the arm (SESSION_LOG 2026-09-27; data in include/edgeneuro/control/mearm_envelope_data.hpp, GENERATED by
// tools/gen_mearm_envelope.py from the raw measurement files). Three layers: properties with a synthetic table that
// does not depend on the data; the real table checked against the stops the person pressed Enter at (independent
// literals -- the raw data is the arbiter); and parity with the Python reference via data/envelope_golden.csv.
#include <cmath>
#include <fstream>
#include <limits>
#include <sstream>
#include <string>

#include <catch2/catch_test_macros.hpp>

#include "edgeneuro/control/mearm_envelope.hpp"

using edgeneuro::PulseEnvelope;

namespace {
constexpr float kNaN = std::numeric_limits<float>::quiet_NaN();
constexpr float kInf = std::numeric_limits<float>::infinity();

constexpr unsigned kS[4] = {1500u, 1575u, 1650u, 1800u};
constexpr unsigned kLo[4] = {500u, 500u, 500u, 500u};
constexpr unsigned kHi[4] = {1500u, 1850u, 1850u, 1600u};
PulseEnvelope synth() { return PulseEnvelope(kS, kLo, kHi, 4u, 1500u, 1500u); }
}  // namespace

TEST_CASE("a point inside the envelope is unchanged", "[envelope]") {
    const auto p = synth().clamp(1575.0f, 1000.0f);
    REQUIRE((p.shoulder == 1575u && p.elbow == 1000u));
}

TEST_CASE("the shoulder never leaves the measured breakpoints", "[envelope]") {
    for (float s : {-1e9f, 0.0f, 1499.0f, 1801.0f, 2100.0f, 1e9f, kInf, -kInf}) {
        const auto p = synth().clamp(s, 1000.0f);
        INFO("shoulder=" << s);
        REQUIRE(p.shoulder >= 1500u);
        REQUIRE(p.shoulder <= 1800u);
    }
}

TEST_CASE("at a breakpoint its own window applies", "[envelope]") {
    REQUIRE(synth().clamp(1500.0f, 1800.0f).elbow == 1500u);
    REQUIRE(synth().clamp(1575.0f, 1900.0f).elbow == 1850u);
    REQUIRE(synth().clamp(1800.0f, 1900.0f).elbow == 1600u);
}

TEST_CASE("between two breakpoints the more conservative neighbour wins -- no interpolation", "[envelope]") {
    REQUIRE(synth().clamp(1525.0f, 1900.0f).elbow == 1500u);    // between 1500 (<=1500) and 1575 (<=1850)
    REQUIRE(synth().clamp(1725.0f, 1900.0f).elbow == 1600u);    // between 1650 (<=1850) and 1800 (<=1600)
    REQUIRE(synth().clamp(1600.0f, 1900.0f).elbow == 1850u);    // between 1575 and 1650: both 1850
}

TEST_CASE("the elbow is kept above the lower edge too", "[envelope]") {
    REQUIRE(synth().clamp(1575.0f, 0.0f).elbow == 500u);
    REQUIRE(synth().clamp(1575.0f, -kInf).elbow == 500u);
    REQUIRE(synth().clamp(1575.0f, kInf).elbow == 1850u);
}

TEST_CASE("clamping twice changes nothing", "[envelope]") {
    for (float s = 1300.0f; s < 2000.0f; s += 37.0f) {
        for (float e = 300.0f; e < 2100.0f; e += 61.0f) {
            const auto once = synth().clamp(s, e);
            const auto twice = synth().clamp(static_cast<float>(once.shoulder), static_cast<float>(once.elbow));
            REQUIRE((once.shoulder == twice.shoulder && once.elbow == twice.elbow));
        }
    }
}

TEST_CASE("a NaN input goes to the rest pose", "[envelope]") {
    for (auto [s, e] : {std::pair{kNaN, 1000.0f}, std::pair{1600.0f, kNaN}, std::pair{kNaN, kNaN}}) {
        const auto p = synth().clamp(s, e);
        REQUIRE((p.shoulder == 1500u && p.elbow == 1500u));
    }
}

TEST_CASE("results are whole microseconds, rounded to nearest", "[envelope]") {
    const auto p = synth().clamp(1612.4f, 1000.6f);
    REQUIRE((p.shoulder == 1612u && p.elbow == 1001u));
    const auto q = synth().clamp(1612.6f, 1000.4f);       // (rounding and truncating agree on .4: this one tells them apart)
    REQUIRE((q.shoulder == 1613u && q.elbow == 1000u));
}

TEST_CASE("between breakpoints the HIGHER lower edge wins as well as the lower upper edge", "[envelope]") {
    // the real table's lower edges are all 500, which cannot show that: use a table where they differ
    const unsigned s[3] = {1500u, 1600u, 1700u};
    const unsigned lo[3] = {600u, 500u, 700u};
    const unsigned hi[3] = {1500u, 1800u, 1700u};
    PulseEnvelope env(s, lo, hi, 3u, 1500u, 1500u);
    REQUIRE(env.clamp(1550.0f, 0.0f).elbow == 600u);      // between 1500 (lo 600) and 1600 (lo 500) -> 600
    REQUIRE(env.clamp(1650.0f, 0.0f).elbow == 700u);      // between 1600 (lo 500) and 1700 (lo 700) -> 700
    REQUIRE(env.clamp(1550.0f, 5000.0f).elbow == 1500u);  // and the lower upper edge, 1500 vs 1800
    REQUIRE(env.clamp(1650.0f, 5000.0f).elbow == 1700u);  // 1800 vs 1700
}

TEST_CASE("an empty table or an empty window fails safe to the rest pose", "[envelope]") {
    const unsigned s1[1] = {1500u}, lo1[1] = {1000u}, hi1[1] = {900u};        // lo > hi
    PulseEnvelope empty_window(s1, lo1, hi1, 1u, 1500u, 1500u);
    const auto p = empty_window.clamp(1500.0f, 1000.0f);
    REQUIRE((p.shoulder == 1500u && p.elbow == 1500u));
    PulseEnvelope none(s1, lo1, hi1, 0u, 1500u, 1500u);
    const auto q = none.clamp(1700.0f, 1700.0f);
    REQUIRE((q.shoulder == 1500u && q.elbow == 1500u));
}

// ---- the REAL table, against the stops the person pressed Enter at (independent literals) ----

TEST_CASE("the real envelope never allows a pulse where the person pressed Enter", "[envelope][real]") {
    const auto& env = edgeneuro::mearm::envelope();
    // (shoulder, elbow) where the elbow was stopped on its way UP: shoulder 1500 collided with the base plate at
    // 1575 and 1775; shoulder 1800 bound (labelled linkage) at 1700 and 1675
    struct { float s, stop; } up[] = {{1500.0f, 1575.0f}, {1500.0f, 1775.0f}, {1800.0f, 1700.0f}, {1800.0f, 1675.0f}};
    for (const auto& u : up) {
        INFO("shoulder " << u.s << " elbow stop " << u.stop);
        REQUIRE(env.clamp(u.s, u.stop).elbow < static_cast<unsigned>(u.stop));
    }
    // the shoulder stopped by itself BELOW rest (base plate) at 1350 / 1400 / 1425
    for (float stop : {1350.0f, 1400.0f, 1425.0f}) {
        REQUIRE(env.clamp(stop, 1500.0f).shoulder > static_cast<unsigned>(stop));
    }
}

TEST_CASE("the real envelope stays inside the measured region", "[envelope][real]") {
    const auto& env = edgeneuro::mearm::envelope();
    for (float s = 1200.0f; s <= 2100.0f; s += 5.0f) {
        for (float e = 300.0f; e <= 2000.0f; e += 25.0f) {
            const auto p = env.clamp(s, e);
            REQUIRE(p.shoulder >= 1500u);
            // nothing beyond the highest measured shoulder is claimed
            REQUIRE(p.shoulder <= edgeneuro::mearm::envelope_data::kShoulderUs[edgeneuro::mearm::envelope_data::kCount - 1u]);
            REQUIRE(p.elbow >= 500u);
            REQUIRE(p.elbow <= 1850u);                    // the elbow servo's own measured maximum
        }
    }
}

TEST_CASE("the rest pose is inside the real envelope", "[envelope][real]") {
    const auto p = edgeneuro::mearm::envelope().clamp(static_cast<float>(edgeneuro::mearm::kShoulderRestUs),
                                                     static_cast<float>(edgeneuro::mearm::kElbowRestUs));
    REQUIRE((p.shoulder == edgeneuro::mearm::kShoulderRestUs && p.elbow == edgeneuro::mearm::kElbowRestUs));
}

TEST_CASE("C++ clamp reproduces every row of the Python golden table", "[envelope][real]") {
    std::ifstream f(std::string(EDGENEURO_DATA_DIR) + "/envelope_golden.csv");
    REQUIRE(f.is_open());
    std::string line;
    std::getline(f, line);
    const auto& env = edgeneuro::mearm::envelope();
    int rows = 0;
    while (std::getline(f, line)) {
        std::istringstream ss(line);
        std::string a, b, c, d;
        std::getline(ss, a, ','); std::getline(ss, b, ','); std::getline(ss, c, ','); std::getline(ss, d, ',');
        const auto p = env.clamp(std::stof(a), std::stof(b));
        INFO("in=(" << a << "," << b << ")");
        REQUIRE(p.shoulder == static_cast<unsigned>(std::stoi(c)));
        REQUIRE(p.elbow == static_cast<unsigned>(std::stoi(d)));
        ++rows;
    }
    REQUIRE(rows >= 500);
}
