#pragma once

// GENERATED by tools/gen_mearm_envelope.py from the raw measurement files
//   mearm_linkage_20260927-113901.json, mearm_linkage_20260927-115438.json, mearm_linkage_20260927-120445.json, mearm_linkage_20260928-160307.json, mearm_linkage_20260928-170204.json
// -- do not edit by hand (tools/test_gen_mearm_envelope.py fails if this file is stale).
//
// The real MEArm's safe (shoulder, elbow) envelope in servo pulse width, per MEASURED shoulder position
// (SESSION_LOG 2026-09-27). Any stop counts, whatever its cause. Coarse and conservative: between two measured
// positions PulseEnvelope intersects the two windows, and the shoulder may not leave the measured range.

namespace edgeneuro::mearm::envelope_data {

constexpr unsigned kCount = 8u;
constexpr unsigned kShoulderUs[kCount] = {1500u, 1575u, 1650u, 1800u, 1875u, 1950u, 2025u, 2100u};
constexpr unsigned kElbowLoUs[kCount] = {500u, 500u, 500u, 500u, 500u, 500u, 500u, 500u};
constexpr unsigned kElbowHiUs[kCount] = {1500u, 1850u, 1850u, 1600u, 1425u, 1425u, 1150u, 1000u};

}  // namespace edgeneuro::mearm::envelope_data
