#pragma once

// GENERATED by tools/mujoco_bridge/gen_real_golden.py from mearm_angles_20260927-133753_signed.json
// -- do not edit by hand (tools/mujoco_bridge/test_real_golden.py fails if this file is stale).
//
// The real MEArm's link elevations (degrees above horizontal) against servo pulse width, measured with a phone
// inclinometer (SESSION_LOG 2026-09-27):  elevation = at_1500 + slope * (pulse - 1500).

namespace edgeneuro::mearm::angle_data {

constexpr float kUpperArmAt1500Deg = 50.106382979f;
constexpr float kUpperArmSlopeDegPerUs = 0.066950355f;
constexpr float kForearmAt1500Deg = -54.913793103f;
constexpr float kForearmSlopeDegPerUs = -0.081724138f;

}  // namespace edgeneuro::mearm::angle_data
