#pragma once

// GENERATED by tools/mujoco_bridge/gen_calibration_header.py from the golden calibration
// (captured 2026-09-13 16:35:48) -- do not edit by hand. Only what the board BOOTS with: a
// fresh calibration reaches it over UART from run_demo_live.py (mearm_calibration_link), no re-flash needed.
//
// The upper-arm IMU's raw gravity vectors (g) at the calibration poses HANG / FORWARD / LEFT_TWIST / RIGHT_TWIST, and the
// firmware's elbow reading (rad) with the arm straight: what mearm::pathb::Calibration is built from on the chip. Plus
// the arm's comfortable left/right reach (raw vectors), where the base hits its ends -- or kHasBaseReach = false.

namespace edgeneuro::mearm::calibration_data {

constexpr float kHangX = 0.992636924f;
constexpr float kHangY = 0.046786648f;
constexpr float kHangZ = 0.265019933f;
constexpr float kForwardX = 0.033408708f;
constexpr float kForwardY = -0.010959840f;
constexpr float kForwardZ = 1.024878189f;
constexpr float kLeftX = 0.122860848f;
constexpr float kLeftY = 0.451800790f;
constexpr float kLeftZ = 0.918383905f;
constexpr float kRightX = 0.112252314f;
constexpr float kRightY = -0.461118933f;
constexpr float kRightZ = 0.899954676f;
constexpr float kZeroElbow = 0.434012124f;
constexpr bool kHasBaseReach = false;
constexpr float kBaseReachLeftX = 0.000000000f;
constexpr float kBaseReachLeftY = 0.000000000f;
constexpr float kBaseReachLeftZ = 0.000000000f;
constexpr float kBaseReachRightX = 0.000000000f;
constexpr float kBaseReachRightY = 0.000000000f;
constexpr float kBaseReachRightZ = 0.000000000f;

}  // namespace edgeneuro::mearm::calibration_data
