#!/usr/bin/env python3
"""The real MEArm's safe (shoulder, elbow) envelope in servo pulse width, built from the raw measurement files.

    python3 tools/gen_mearm_envelope.py

writes include/edgeneuro/control/mearm_envelope_data.hpp (the table the firmware clamp uses) and
data/envelope_golden.csv (what tests/test_pulse_envelope.cpp checks the C++ clamp against).

Evidence (SESSION_LOG 2026-09-27): only the three runs made with the fixed tool AND cause labels -- run 1 had a tool that
jumped and lost steps, run 2 had no cause labels (collisions were mixed in as if they were the linkage). Every stop of ANY
cause counts (a claw hitting the base plate is as bad for the hardware as a linkage binding). The table is deliberately
coarse and conservative:
  * one elbow window per MEASURED shoulder position (repeats combined: the lowest upper stop, the highest lower stop,
    each pulled inward by 3 steps),
  * BETWEEN two measured positions the two windows are INTERSECTED -- never interpolated,
  * the shoulder may only be where it was actually measured (no claim about anything beyond the first / last point).
"""
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import measure_linkage_region as m  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "include" / "edgeneuro" / "control" / "mearm_envelope_data.hpp"
GOLDEN = ROOT / "data" / "envelope_golden.csv"
SOURCES = ("mearm_linkage_20260927-113901.json", "mearm_linkage_20260927-115438.json",
           "mearm_linkage_20260927-120445.json", "mearm_linkage_20260928-160307.json",
           "mearm_linkage_20260928-170204.json")
REST_SHOULDER = REST_ELBOW = 1500          # NaN input goes here (inside the envelope: see the tests)


def build_table(records, margin_steps=3):
    env = m.safe_envelope(records, margin_steps)
    wins = sorted(env["windows"], key=lambda w: w["shoulder"])
    table = {"shoulders": [int(w["shoulder"]) for w in wins],
             "lo": [int(round(w["lo"])) for w in wins],
             "hi": [int(round(w["hi"])) for w in wins]}
    if not table["shoulders"]:
        raise ValueError("no usable shoulder position in the records")
    for s, lo, hi in zip(table["shoulders"], table["lo"], table["hi"]):
        if lo >= hi:
            raise ValueError(f"empty elbow window at shoulder {s}: {lo}..{hi}")
    return table


def shoulder_range(table):
    """The shoulder may only be where it was measured."""
    return table["shoulders"][0], table["shoulders"][-1]


def _window(table, s):
    bp = table["shoulders"]
    for i, b in enumerate(bp):
        if s == b:
            return table["lo"][i], table["hi"][i]
    for i in range(len(bp) - 1):
        if bp[i] < s < bp[i + 1]:                       # between two measured points: the more conservative of the two
            return max(table["lo"][i], table["lo"][i + 1]), min(table["hi"][i], table["hi"][i + 1])
    raise AssertionError("unreachable: s is inside the breakpoints")


def clamp(table, shoulder_us, elbow_us):
    """(shoulder, elbow) whole microseconds inside the envelope. Non-finite input -> the rest pose."""
    if math.isnan(shoulder_us) or math.isnan(elbow_us):
        return REST_SHOULDER, REST_ELBOW
    lo_s, hi_s = shoulder_range(table)
    s = int(math.floor(min(max(shoulder_us, lo_s), hi_s) + 0.5))
    lo, hi = _window(table, s)
    e = int(math.floor(min(max(elbow_us, lo), hi) + 0.5))
    return s, e


def render_header(table):
    arr = lambda v: ", ".join(f"{x}u" for x in v)
    return f'''#pragma once

// GENERATED by tools/gen_mearm_envelope.py from the raw measurement files
//   {", ".join(SOURCES)}
// -- do not edit by hand (tools/test_gen_mearm_envelope.py fails if this file is stale).
//
// The real MEArm's safe (shoulder, elbow) envelope in servo pulse width, per MEASURED shoulder position
// (SESSION_LOG 2026-09-27). Any stop counts, whatever its cause. Coarse and conservative: between two measured
// positions PulseEnvelope intersects the two windows, and the shoulder may not leave the measured range.

namespace edgeneuro::mearm::envelope_data {{

constexpr unsigned kCount = {len(table["shoulders"])}u;
constexpr unsigned kShoulderUs[kCount] = {{{arr(table["shoulders"])}}};
constexpr unsigned kElbowLoUs[kCount] = {{{arr(table["lo"])}}};
constexpr unsigned kElbowHiUs[kCount] = {{{arr(table["hi"])}}};

}}  // namespace edgeneuro::mearm::envelope_data
'''


def render_golden(table):
    lines = ["shoulder_in,elbow_in,shoulder_out,elbow_out"]
    for s in range(1300, 2125, 25):
        for e in range(400, 1975, 50):
            so, eo = clamp(table, s, e)
            lines.append(f"{s},{e},{so},{eo}")
    return "\n".join(lines) + "\n"


def write(header_path=HEADER, golden_path=GOLDEN):
    table = build_table(m.load_records([ROOT / "data" / n for n in SOURCES]))
    Path(header_path).parent.mkdir(parents=True, exist_ok=True)
    Path(golden_path).parent.mkdir(parents=True, exist_ok=True)
    Path(header_path).write_text(render_header(table))
    Path(golden_path).write_text(render_golden(table))
    return table


if __name__ == "__main__":
    t = write()
    print(f"wrote {HEADER}\nwrote {GOLDEN}")
    for s, lo, hi in zip(t["shoulders"], t["lo"], t["hi"]):
        print(f"  shoulder {s}: elbow {lo}..{hi}")
